name: Update README

on:
  push:
    paths:
      - emulators.json  # Trigger when this file is updated.
  workflow_dispatch:  # Allow manual triggers.

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Debug: List repository contents
      - name: List repository contents
        run: ls -la

      # Debug: Show Git status
      - name: Show Git status
        run: git status

      # Run the script to update README.md
      - name: Run script to update README.md
        run: python update_readme.py

      # Debug: Check README content
      - name: Debug README content
        run: cat README.md

      # Check for changes
      - name: Check for changes
        id: git_diff
        run: |
          git diff --quiet || echo "changes_detected=true" >> $GITHUB_ENV
          echo "changes_detected=false" >> $GITHUB_ENV

      # Commit and push changes if detected
      - name: Commit and push changes
        if: env.changes_detected == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto-update README.md with supported emulators"
          git push

      # No changes detected
      - name: No changes detected
        if: env.changes_detected == 'false'
        run: echo "No changes detected. Skipping commit."
