name: Update README

on:
  push:
    paths:
      - emulators.json
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Step 3: Install dependencies (if needed)
      - name: Install dependencies
        run: pip install -r requirements.txt || echo "No requirements.txt found"

      # Step 4: Run the update script
      - name: Update README.md
        run: python update_readme.py

      # Step 5: Check if there are changes
      - name: Check for changes in README.md
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --exit-code || echo "changes_detected=true" >> $GITHUB_ENV

      # Step 6: Commit and push changes (if any)
      - name: Commit and push changes if detected
        if: env.changes_detected == 'true'
        run: |
          git checkout -b update-readme-branch || git checkout main
          git commit -m "Auto-update README.md based on emulators.json" || echo "No changes to commit"
          git push origin HEAD:main || echo "Push failed"

      # Step 7: Force update README.md if manually triggered
      - name: Force update README.md on manual trigger
        if: github.event_name == 'workflow_dispatch'
        run: |
          git checkout -b update-readme-branch || git checkout main
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Manual trigger: Force update README.md" || echo "No changes to commit"
          git push origin HEAD:main || echo "Push failed"
